// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qafnluiknsseteeaynge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZm5sdWlrbnNzZXRlZWF5bmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjkyMjIsImV4cCI6MjA2MjgwNTIyMn0.CzEenZhW5kZ6Kn0HdbDQxy-7Q5aru7Uq8ZjTzfkfAM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);