
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qafnluiknsseteeaynge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZm5sdWlrbnNzZXRlZWF5bmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjkyMjIsImV4cCI6MjA2MjgwNTIyMn0.CzEenZhW5kZ6Kn0HdbDQxy-7Q5aru7Uq8ZjTzfkfAM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize storage buckets if they don't exist
const initializeStorage = async () => {
  try {
    // Check if tenders bucket exists, create if not
    const { data: tendersBuckets } = await supabase.storage.getBucket('tenders');
    if (!tendersBuckets) {
      await supabase.storage.createBucket('tenders', {
        public: true,
        fileSizeLimit: 10485760 // 10MB limit
      });
      console.log('Created tenders storage bucket');
    }
    
    // Check if offers bucket exists, create if not
    const { data: offersBuckets } = await supabase.storage.getBucket('offers');
    if (!offersBuckets) {
      await supabase.storage.createBucket('offers', {
        public: true,
        fileSizeLimit: 10485760 // 10MB limit
      });
      console.log('Created offers storage bucket');
    }
  } catch (error) {
    console.error('Error initializing storage buckets:', error);
  }
};

// Call the initialization function
initializeStorage();
